name: ballauto
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: ^3.7.0-323.0.dev


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8 # เพิ่มแพ็กเกจสำหรับไอคอน
  shared_preferences: ^2.1.1 # package สำหรับเก็บข้อมูลในเครื่อง
  firebase_core: ^2.27.1    # package หลักสำหรับเชื่อมต่อกับ Firebase
  firebase_auth: ^4.17.9    # package สำหรับระบบล็อกอิน
  cloud_firestore: ^4.15.9  # package สำหรับฐานข้อมูล
  firebase_analytics: ^10.8.10  # เครื่องมือที่ช่วยเก็บข้อมูลและวิเคราะห์พฤติกรรมการใช้งานแอพของผู้ใช้
  clipboard: ^0.1.3  # package สำหรับคัดลอกข้อมูลไปยังคลิปบอร์ด
  http: ^1.2.2  # package สำหรับการทำ HTTP request
  xml: ^6.5.0  # package สำหรับการจัดการกับข้อมูล XML in sms gateway
  intl: ^0.19.0 # package สำหรับการจัดการกับข้อมูลวันที่และเวลา
  geolocator: ^12.0.0  # เพิ่มแพ็กเกจสำหรับดึงตำแหน่ง
  sensors_plus: ^6.1.1  # เพิ่มแพ็กเกจสำหรับอ่านค่า accelerometer and gyroscope
  flutter_local_notifications: ^19.1.0  # อัปเดตเป็นเวอร์ชันล่าสุดพร้อม linux support
  flutter_foreground_task: ^6.0.0  # รัน foreground service ดักจับการล้มแม้แอพเบื้องหลัง
  url_launcher: ^6.1.7 # เพิ่มแพ็กเกจสำหรับการเรียกเปิดไปที่อื่น

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/images/